AWSTemplateFormatVersion: '2010-09-09'
Description: Create Instance Profiles for AEM Stack (qs-1r4pm2npq)
Parameters:
  AOCStackPrefix:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
Resources:
  AuthorDispatcherInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: AuthorDispatcherRole
    Type: AWS::IAM::InstanceProfile
  AuthorDispatcherRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/CloudWatchAgentServerPolicy
      - !Ref AOCS3ReadAccessPolicy
      - !Ref AOCS3WriteAccessPolicy
      - !Ref AOCBasePolicy
      Path: /
    Type: AWS::IAM::Role
  AuthorInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: AuthorRole
    Type: AWS::IAM::InstanceProfile
  AuthorRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/CloudWatchAgentServerPolicy
      - !Ref AOCS3ReadAccessPolicy
      - !Ref AOCS3WriteAccessPolicy
      - !Ref AOCBasePolicy
      - !Ref AOCBackupPolicy
      Path: /
    Type: AWS::IAM::Role
  OrchestratorInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: OrchestratorRole
    Type: AWS::IAM::InstanceProfile
  OrchestratorRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/CloudWatchAgentServerPolicy
      - !Ref AOCS3ReadAccessPolicy
      - !Ref AOCS3WriteAccessPolicy
      - !Ref AOCBasePolicy
      - !Ref AOCOrchestrationAccessPolicy
      Path: /
    Type: AWS::IAM::Role
  PublishDispatcherInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: PublishDispatcherRole
    Type: AWS::IAM::InstanceProfile
  PublishDispatcherRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/CloudWatchAgentServerPolicy
      - !Ref AOCS3ReadAccessPolicy
      - !Ref AOCS3WriteAccessPolicy
      - !Ref AOCBasePolicy
      Path: /
    Type: AWS::IAM::Role
  PublishInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: PublishRole
    Type: AWS::IAM::InstanceProfile
  PublishRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W11
          reason: "Skip IAM Resource permission check for IAM Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/CloudWatchAgentServerPolicy
      - !Ref AOCS3ReadAccessPolicy
      - !Ref AOCS3WriteAccessPolicy
      - !Ref AOCBasePolicy
      - !Ref AOCBackupPolicy
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ec2:DescribeVolumes
            Effect: Allow
            Resource: '*'
          - Action:
            - ec2:CreateVolume
            - ec2:DeleteVolume
            - ec2:DetachVolume
            - ec2:CreateTags
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:volume/*"
          - Action:
            - ec2:AttachVolume
            - ec2:ModifyInstanceAttribute
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
          Version: '2012-10-17'
        PolicyName: PublishRolePolicy
    Type: AWS::IAM::Role
  AOCBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W13
          reason: "Skip IAM Resource check"
    Properties:
      Description: Manage Policy required for all AOC components
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - ec2:CreateTags
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
        - Action:
          - ec2:DescribeTags
          - ec2:DescribeInstances
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
  AOCBackupPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W13
          reason: "Skip IAM Resource check"
    Properties:
      Description: Manage Policy required for all AOC components
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:DescribeLaunchConfigurations
          - ec2:DescribeSnapshots
          Effect: Allow
          Resource: '*'
        - Action:
          - ec2:CreateSnapshot
          - ec2:CreateTags
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}::snapshot/*"
        - Action:
          - autoscaling:CreateLaunchConfiguration
          - autoscaling:DeleteLaunchConfiguration
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:autoscaling:${AWS::Region}:${AWS::AccountId}:launchConfigurationName/*"
        - Action:
          - autoscaling:UpdateAutoScalingGroup
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*"
        Version: 2012-10-17
  AOCS3ReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Manage Policy to allow EC2 instances read access to AOC S3 Stack Prefix
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - s3:Get*
          - s3:List*
          Effect: Allow
          Resource:
            - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/s3databucketname:1}}"
                  - !Sub "/${AOCStackPrefix}"
            - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/s3databucketname:1}}"
                  - !Sub "/${AOCStackPrefix}/*"
        Version: 2012-10-17
  AOCS3WriteAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Manage Policy to allow EC2 instances read & write access to AOC S3 Stack Prefix
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - s3:Put*
          Effect: Allow
          Resource:
            - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/s3databucketname:1}}"
                  - !Sub "/${AOCStackPrefix}"
            - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/s3databucketname:1}}"
                  - !Sub "/${AOCStackPrefix}/*"
        Version: 2012-10-17
  AOCOrchestrationAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W13
          reason: "Skip IAM Resource check"
    Properties:
      Description: Manage Policy to allow EC2 instances read & write access to AOC S3 Stack Prefix
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - autoscaling:DescribeAutoScalingGroups
          - elasticloadbalancing:DescribeLoadBalancers
          - ec2:describeInstanceAttribute
          Effect: Allow
          Resource: '*'
        - Action:
          - cloudformation:DescribeStackResources
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*/*"
        - Action:
          - ec2:TerminateInstances
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
        - Action:
          - autoscaling:setDesiredCapacity
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*"
        - Action:
          - ec2:CreateSnapshot
          - ec2:CreateTags
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}::snapshot/*"
        - Action:
          - cloudwatch:PutMetricAlarm
          - cloudwatch:deleteAlarms
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:*"
        - Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          Effect: Allow
          Resource: !Sub "arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*"
        Version: 2012-10-17
  AuthorDispatcherInstanceProfileParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/authordispatcherinstanceprofile
      Description: Author Dispatcher Instance Profile
      Type: String
      Value:
        Ref: AuthorDispatcherInstanceProfile
  AuthorDispatcherRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/authordispatcherrolearn
      Description: Author Dispatcher Instance Role ARN
      Type: String
      Value:
        Fn::GetAtt: AuthorDispatcherRole.Arn
  AuthorInstanceProfileParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/authorinstanceprofile
      Description: Author Instance Profile
      Type: String
      Value:
        Ref: AuthorInstanceProfile
  AuthorRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/authorrolearn
      Description: Author Instance Role ARN
      Type: String
      Value:
        Fn::GetAtt: AuthorRole.Arn
  OrchestratorInstanceProfileParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/orchestratorinstanceprofile
      Description: Orchestrator Instance Profile
      Type: String
      Value:
        Ref: OrchestratorInstanceProfile
  OrchestratorRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/orchestratorrolearn
      Description: Orchestrator Instance Role ARN
      Type: String
      Value:
        Fn::GetAtt: OrchestratorRole.Arn
  PublishDispatcherInstanceProfileParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/publishdispatcherinstanceprofile
      Description: Publish Dispatcher Instance Profile
      Type: String
      Value:
        Ref: PublishDispatcherInstanceProfile
  PublishDispatcherRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/publishdispatcherrolearn
      Description: PublishDispatcher Instance Role ARN
      Type: String
      Value:
        Fn::GetAtt: PublishDispatcherRole.Arn
  PublishInstanceProfileParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/publishinstanceprofile
      Description: Publish Instance Profile
      Type: String
      Value:
        Ref: PublishInstanceProfile
  PublishRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AOCStackPrefix}/iam/publishrolearn
      Description: Publish Instance Role ARN
      Type: String
      Value:
        Fn::GetAtt: PublishRole.Arn
