AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  UsePublishDataVolSnapshotCondition:
    Fn::Equals:
    - Ref: UsePublishDataVolSnapshotParameter
    - true
Description: Create the Compute resources for the AEM Publish
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  AOCStackPrefix:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  PublishASGAvailabilityZoneListParameter:
    Description: The Publish Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PublishDataVolSizeParameter:
    Description: The Publish Instances Data EBS Volume Size
    Type: Number
  PublishDataVolSnapshotParameter:
    Description: The Publish Data Volume Snapshot Id
    Type: String
  PublishImageParameter:
    Description: The Publish Image Id
    Type: AWS::EC2::Image::Id
  PublishImageRootDevice:
    Default: /dev/sda1
    Description: The root device name for the Publish Image Id
    Type: String
  PublishImageDataDevice:
    Default: /dev/sdb
    Description: The data device name for the Publish Image Id
    Type: String
  PublishInstanceTypeParameter:
    Description: The Publish Instance Type
    Type: String
  PublishRootVolSizeParameter:
    Description: Publish Instances Root EBS Volume Size
    Type: Number
  UsePublishDataVolSnapshotParameter:
    AllowedValues:
    - true
    - false
    Description: Wheather to use the Publish Snapshot Data Volume.
    Type: String
Resources:
  PublishAutoScalingGroup:
    Properties:
      AvailabilityZones:
        Ref: PublishASGAvailabilityZoneListParameter
      Cooldown: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/asg/cooldown:1}}"
      DesiredCapacity: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/asg/desiredcapacity:1}}"
      HealthCheckGracePeriod: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/asg/healthcheckgraceperiod:1}}"
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: PublishLaunchConfiguration
      MaxSize: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/asg/maxsize:1}}"
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupMinSize
        - GroupMaxSize
        - GroupDesiredCapacity
        - GroupInServiceInstances
        - GroupPendingInstances
        - GroupStandbyInstances
        - GroupTerminatingInstances
        - GroupTotalInstances
      MinSize: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/asg/minsize:1}}"
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN: !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/aemasgeventtopic:1}}"
      Tags:
      - Key: Name
        PropagateAtLaunch: true
        Value: AEM Publish
      - Key: StackPrefix
        PropagateAtLaunch: true
        Value:
          Ref: AOCStackPrefix
      - Key: Component
        PropagateAtLaunch: true
        Value: publish
      VPCZoneIdentifier:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/privatesubnet1aid:1}}"
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/privatesubnet2aid:1}}"
    Type: AWS::AutoScaling::AutoScalingGroup
  PublishLaunchConfiguration:
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName:
          Ref: PublishImageRootDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted: true
          VolumeSize:
            Ref: PublishRootVolSizeParameter
          VolumeType: gp2
      - DeviceName:
          Ref: PublishImageDataDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted: true
          SnapshotId:
            Fn::If:
            - UsePublishDataVolSnapshotCondition
            - Ref: PublishDataVolSnapshotParameter
            - Ref: AWS::NoValue
          VolumeSize:
            Ref: PublishDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile: !Sub "{{resolve:ssm:/${AOCStackPrefix}/iam/publishinstanceprofile:1}}"
      ImageId:
        Ref: PublishImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishInstanceTypeParameter
      KeyName: !Sub "{{resolve:ssm:/${AOCStackPrefix}/ec2/keypairname:1}}"
      SecurityGroups:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/sg/publish:1}}"
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${AOCStackPrefix}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${AOCStackPrefix} publish ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::AutoScaling::LaunchConfiguration

  WarningPublishMemoryHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      AlarmDescription: Memory Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Warning-Publish-MemoryHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: "System/Linux"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalPublishMemoryHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      AlarmDescription: Memory Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Critical-Publish-MemoryHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: "System/Linux"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningPublishRootDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Warning-Publish-RootDiskSpaceHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/"
        - Name: Filesystem
          Value: "/"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalPublishRootDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Critical-Publish-RootDiskSpaceHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/"
        - Name: Filesystem
          Value: "/"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningPublishDataDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Warning-Publish-DataDiskSpaceHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/mnt/ebs1"
        - Name: Filesystem
          Value: "/mnt/ebs1"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalPublishDataDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Critical-Publish-DataDiskSpaceHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/mnt/ebs1"
        - Name: Filesystem
          Value: "/mnt/ebs1"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningPublishCPUUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      AlarmDescription: CPU Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Warning-Publish-CPUHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/warningalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Maximum
      Threshold: 60
    Type: AWS::CloudWatch::Alarm
  CriticalPublishCPUUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      AlarmDescription: CPU Utilization is high
      AlarmName:
        Fn::Sub:
          - "${AOCStackPrefix}-Critical-Publish-CPUHighAlarm"
          - AOCStackPrefix:
              Ref: 'AOCStackPrefix'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      OKActions:
        - !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/criticalalarmnotificationtopic:1}}"
      Period: 300
      Statistic: Maximum
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
