// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Security
The login credentials of the AEM system users are stored as json file `system_users_credentials.json` on S3 at the location `s3://S3DataBucketName/AOCStackPrefix/`. `S3DataBucketName` is the name of the provided (or generated) S3 Bucket and `AOCStackPrefix` is the provided stack prefix (e.g. `s3://aem-opencloud/aoc-stack-1/system-users-credentials.json`.)

To login to AEM use the credentials for the `admin` user.

WARNING: Changing the password of an AEM System User may cause system instabilities and is therefore not recommended.

If you changed the password of an AEM system user, do the following:

. Update the `system_users_credentials.json` with the new password.
. Make sure the same password for the user is set on the AEM Author & AEM Publish EC2 instances.
. If you change the password of the `orchestrator` user, restart or terminate the AEM Orchestrator EC2 instance and wait until the new one came up successfully by monitoring the EC2 tag `ComponentInitStatus`.
. If you change the password of the `replicator` user, update all agents on the AEM Author & AEM Publish EC2 instances with the new password. As an alternative, you can also terminate the AEM Publish instances one by one. Before terminating the second AEM Publish instance, verify provisioning of the recovered AEM Publish EC2 instance was successful by monitoring the EC2 tag `ComponentInitStatus`.
