### Beginn common configurations
common::aws_region: <%aws_region%>

# Common proxy settings
common::proxy_enabled: False
common::proxy_protocol: ''
common::proxy_host: ''
common::proxy_port: ''
common::proxy_user: ''
common::proxy_password: ''
common::proxy_noproxy:
  - localhost
  - 127.0.0.1
  - 10.0.0.0/8
  - 169.254.169.254
  - 169.254.0.0/16
  - 172.16.0.0/16
  - 192.168.0.0/24
  - aemopencloud.cms
  - elb.amazonaws.com

common::login_ready_max_tries: '120'
common::login_ready_base_sleep_seconds: '15'
common::login_ready_max_sleep_seconds: '30'

# Configure Device names. device alias is used by snapshot_attach.py Depending on the block device driver of the kernel, the device could be attached with a different name than you specified.
common::ami::device_name: /dev/xvdb
common::ami::device_alias: /dev/xvdb

# Service start Post sleep configuration
common::enable_post_start_sleep: True
common::post_start_sleep_seconds: 360

# ssh_public_keys Import
common::ssh_public_keys:
  ec2-user:
    public_key: overwrite-me
    public_key_type: ssh-rsa

# Keystore parameters
common::authorizable_keystore::enable_creation: False
common::authorizable_keystore::enable_certificate_chain_upload: False

# Truststore parameters
common::truststore::enable_creation: False
common::truststore::enable_migration: False
common::truststore::password: changeit

# SAML Configuration parameters
common::saml::enable: False
common::saml::enable_saml_certificate_upload: False
common::saml::configuration:
  add_group_memberships: true
  clock_tolerance: 60
  create_user: true
  default_groups:
  - def-groups
  default_redirect_url: /sites.html
  digest_method: http://www.w3.org/2001/04/xmlenc#sha256
  file: s3://aem-opencloud/certs/saml_certificate.crt
  group_membership_attribute: http://temp/variable/aem-groups
  handle_logout: true
  idp_cert_alias: null
  idp_http_redirect: true
  idp_url: https://federation.prod.com/adfs/ls/IdpInitiatedSignOn.aspx?RequestBinding\=HTTPPost&loginToRp\=https://prod-aemauthor.com/saml_login
  key_store_password: admin
  logout_url: https://federation.prod.com/adfs/ls/IdpInitiatedSignOn.aspx
  name_id_format: urn:oasis:names:tc:SAML:2.0:nameid-format:transient
  path:
  - /
  serial: null
  service_provider_entity_id: https://prod-aemauthor.com/saml_login
  service_ranking: 5002
  signature_method: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
  sp_private_key_alias: null
  synchronize_attributes:x  use_encryption: false
  user_id_attribute: NameID
  user_intermediate_path: null

aem_curator::config_collectd::proxy_protocol: ''
aem_curator::config_collectd::proxy_host: ''
aem_curator::config_collectd::proxy_port: ''
aem_curator::config_collectd::proxy_enabled: False

aem_curator::action_deploy_artifacts::retries_max_tries: 60
aem_curator::action_deploy_artifacts::retries_base_sleep_seconds: 5
aem_curator::action_deploy_artifacts::retries_max_sleep_seconds: 5
aem_curator::action_deploy_artifacts::deployment_sleep_seconds: 10

aem_curator::action_deploy_artifact::retries_max_tries: 60
aem_curator::action_deploy_artifact::retries_base_sleep_seconds: 5
aem_curator::action_deploy_artifact::retries_max_sleep_seconds: 5

# AEM Reconfiguration Parameters
aem_curator::config_author_primary::aem_reconfiguration_run_modes:
aem_curator::config_publish::aem_reconfiguration_run_modes:
# Set to true, as reinstallation of the AEM HealthCheck is not required
aem_curator::config_author_primary::enable_aem_reconfiguratiton_clean_directories: true
aem_curator::config_publish::enable_aem_reconfiguratiton_clean_directories: true
common::aem_healthcheck_version: 1.3.3
common::enable_aem_reconfiguration: False
common::enable_truststore_removal: False
common::certificate_arn: s3://aem-opencloud/certs/aem.cert
common::certificate_key_arn: s3://aem-opencloud/certs/aem.key
common::aem_ssl_keystore_password: 43m0p3ncl0ud
### End common configurations

### Beginn author-primary configuration
aem_curator::config_author_primary::aem_version: '6.5'
aem_curator::config_author_primary::aem_password_reset_version: '1.1.0'
aem_curator::config_author_primary::enable_crxde: True
aem_curator::config_author_primary::enable_default_passwords: False
aem_curator::config_author_primary::jvm_mem_opts: -Xss4m -Xms2048m -Xmx8192m
aem_curator::config_author_primary::jmxremote_port: 5982
aem_curator::config_author_primary::jvm_opts: "-XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+HeapDumpOnOutOfMemoryError"
aem_curator::config_author_primary::author_timeout: 1200
author::aem_system_users:
  admin:
      name: admin
      path: overwrite-me
  authentication-service:
      authorizable_keystore:
          certificate_chain: null
          password: null
          private_key: null
          private_key_alias: null
      name: authentication-service
      path: /home/users/system
  deployer:
      name: deployer
      path: /home/users/q
  exporter:
      name: exporter
      path: /home/users/e
  importer:
      name: importer
      path: /home/users/i
  orchestrator:
      name: orchestrator
      path: /home/users/o
  replicator:
      name: replicator
      path: /home/users/r
  ssl-service:
      authorizable_keystore:
          certificate_chain: null
          password: null
          private_key: null
          private_key_alias: ssl-service
      name: ssl-service
      path: /home/users/system/security
### End author-primary configuration

### Beginn author-standby configuration
aem_curator::config_author_standby::aem_version: '6.5'
aem_curator::config_author_standby::jvm_mem_opts: -Xss4m -Xms2048m -Xmx8192m
aem_curator::config_author_standby::jmxremote_port: 5982
aem_curator::config_author_standby::jvm_opts: "-XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+HeapDumpOnOutOfMemoryError"
aem_curator::action_promote_author_standby_to_primary::aem_version: '6.5'
### End author-standby configuration

### Beginn publish configuration
publish::revert_snapshot_type: live
aem_curator::config_publish::aem_password_reset_version: 1.1.0
aem_curator::config_publish::enable_crxde: True
aem_curator::config_publish::enable_default_passwords: False
aem_curator::config_publish::jvm_mem_opts: -Xss4m -Xms2048m -Xmx8192m
aem_curator::config_publish::jmxremote_port: 5983
aem_curator::config_publish::jvm_opts: "-XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+HeapDumpOnOutOfMemoryError"
aem_curator::config_publish::publish_timeout: 1200
publish::aem_system_users:
  admin:
      name: admin
      path: overwrite-me
  authentication-service:
      authorizable_keystore:
          certificate_chain: null
          password: null
          private_key: null
          private_key_alias: null
      name: authentication-service
      path: /home/users/system
  deployer:
      name: deployer
      path: /home/users/q
  exporter:
      name: exporter
      path: /home/users/e
  importer:
      name: importer
      path: /home/users/i
  orchestrator:
      name: orchestrator
      path: /home/users/o
  replicator:
      name: replicator
      path: /home/users/r
### End publish configuration

### Beginn Orchestrator configuration
# AEM Orchestrator only takes snapshot from Publish instance in a Full-Set architecture, hence it only needs the data volume device name
aem_orchestrator::application_properties::aws_device_name: /dev/xvdb
aem_orchestrator::application_properties::aem_reverse_replication_enable: 'True'
aem_orchestrator::application_properties::alarm_content_health_check_terminate_instance_enable: 'False'
aem_orchestrator::jarfile_checksum_value: 133ad0f9a6c083701b2531b677a4458ebe021af88b3ea0eba87374fb9b12dc94
orchestrator::aem_orchestrator_version: '2.0.1'
orchestrator::stack_manager_stack_name: '-aem-stack-manager-main-stack'
orchestrator::enable_cloudwatch_s3_stream: False
chaos_monkey::include_stack: False
### End Orchestrator configuration

### Beginn aem-tool configuration
aem_curator::config_aem_tools::oak_run_version: '1.10.1'
aem_curator::config_aem_tools::enable_compaction_remove_bak_files: False
aem_curator::config_aem_tools::compaction_remove_bak_files_older_than_in_days: '30'
aem_curator::config_aem_upgrade_tools::enable_upgrade_tools: False
### End aem-tool configuration


### Beginn deploy_on_init configuration
author_publish_dispatcher::enable_deploy_on_init: False
author::enable_deploy_on_init: False
publish::enable_deploy_on_init: False
author_dispatcher::enable_deploy_on_init: False
publish_dispatcher::enable_deploy_on_init: False
### End deploy_on_init configuration

### Beginn logrotation configurations
common::logrotation::config:
  /etc/logrotate.conf:
      rotate: 4

common::logrotation::config_default:
  compress: true
  create: true
  dateext: true
  ifempty: false
  mail: false
  olddir: false
  rotate: 4
  rotate_every: daily
  size: 10M

common::logrotation::rules:
  amazon_ssm:
      missingok: true
      olddir: /var/log/amazon/ssm/
      path: /var/log/amazon/ssm/*.log
      postrotate: /bin/systemctl restart amazon-ssm-agent > /dev/null 2>/dev/null||true
  opencloud_scheduled_jobs:
      missingok: true
      olddir: '%{hiera(''common::log_dir'')}'
      path: '%{hiera(''common::log_dir'')}/cron*.log'
  opencloud_ssm_commands:
      missingok: true
      olddir: '%{hiera(''common::log_dir'')}'
      path: '%{hiera(''common::log_dir'')}/ssm*.log'

author_primary::logrotation:
  config: null
  rules: null

author_standby::logrotation:
  config: null
  rules: null

publish::logrotation:
  config: null
  rules: null

author_dispatcher::logrotation:
  config: null
  rules:
    httpd:
        dateext: true
        delaycompress: true
        ifempty: false
        missingok: true
        olddir: /var/log/httpd
        path: /var/log/httpd/*log
        postrotate: /bin/systemctl reload httpd.service > /dev/null 2>/dev/null||true
        rotate: 5
        rotate_every: day
        sharedscripts: true
        size: 200M

publish_dispatcher::logrotation:
  config: null
  rules:
    httpd:
        dateext: false
        delaycompress: true
        ifempty: false
        missingok: true
        olddir: /var/log/httpd
        path: /var/log/httpd/*log
        postrotate: /bin/systemctl reload httpd.service > /dev/null 2>/dev/null||true
        rotate: 5
        rotate_every: hour
        sharedscripts: true
        size: 200M

aem_orchestrator::logrotation:
  config: null
  rules: null

simianarmy::logrotation:
  config: null
  rules: null
### End logrotation configurations
### Beginn Cron Jobs configurations
author_primary::scheduled_jobs::enable::offline_compaction: False
author_primary::scheduled_jobs::weekday::offline_compaction: "2"
author_primary::scheduled_jobs::hour::offline_compaction: "3"
author_primary::scheduled_jobs::minute::offline_compaction: "0"
author_primary::scheduled_jobs::enable::export: False
author_primary::scheduled_jobs::weekday::export: "0-7"
author_primary::scheduled_jobs::hour::export: "2"
author_primary::scheduled_jobs::minute::export: "0"
author_primary::scheduled_jobs::enable::live_snapshot: True
author_primary::scheduled_jobs::weekday::live_snapshot: "0-7"
author_primary::scheduled_jobs::hour::live_snapshot: "*"
author_primary::scheduled_jobs::minute::live_snapshot: "0"

author_standby::scheduled_jobs::enable::live_snapshot: True
author_standby::scheduled_jobs::weekday::live_snapshot: "0-7"
author_standby::scheduled_jobs::hour::live_snapshot: "0,2-23"
author_standby::scheduled_jobs::minute::live_snapshot: "0"

publish::scheduled_jobs::enable::offline_compaction: False
publish::scheduled_jobs::weekday::offline_compaction: "2"
publish::scheduled_jobs::hour::offline_compaction: "3"
publish::scheduled_jobs::minute::offline_compaction: "0"
publish::scheduled_jobs::enable::export: False
publish::scheduled_jobs::weekday::export: "0-7"
publish::scheduled_jobs::hour::export: "2"
publish::scheduled_jobs::minute::export: "0"
publish::scheduled_jobs::enable::live_snapshot: True
publish::scheduled_jobs::weekday::live_snapshot: "0-7"
publish::scheduled_jobs::hour::live_snapshot: "*"
publish::scheduled_jobs::minute::live_snapshot: "0"

aem_orchestrator::scheduled_jobs::enable::offline_compaction_snapshot: False
aem_orchestrator::scheduled_jobs::weekday::offline_compaction_snapshot: "1"
aem_orchestrator::scheduled_jobs::hour::offline_compaction_snapshot: "1"
aem_orchestrator::scheduled_jobs::minute::offline_compaction_snapshot: "15"
aem_orchestrator::scheduled_jobs::enable::offline_snapshot: False
aem_orchestrator::scheduled_jobs::weekday::offline_snapshot: "2-7"
aem_orchestrator::scheduled_jobs::hour::offline_snapshot: "1"
aem_orchestrator::scheduled_jobs::minute::offline_snapshot: "15"
aem_orchestrator::scheduled_jobs::weekday::cloudwatch_s3_stream: "*"
aem_orchestrator::scheduled_jobs::hour::cloudwatch_s3_stream: "*"
aem_orchestrator::scheduled_jobs::minute::cloudwatch_s3_stream: "30"
action_scheduled_jobs::cloudwatch_log_subscription_arn: overwrite-me

publish_dispatcher::enable_content_healthcheck: False
publish_dispatcher::scheduled_jobs::enable::content_health_check: False
publish_dispatcher::scheduled_jobs::weekday::content_health_check: "*"
publish_dispatcher::scheduled_jobs::hour::content_health_check: "*"
publish_dispatcher::scheduled_jobs::minute::content_health_check: "*"
### End Cron Jobs configurations
